apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nova-hub-app
spec:
  ingressClassName: nginx
  rules:
    - host: nova-hub.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nova-hub-app
                port:
                  number: 80
